[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts']
ffi = true
fs_operations = [{access = "read", path = "./images/"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
